{% set name = "thztools" %}
{% set version = "0.5.5.post0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/thztools-{{ version }}.tar.gz
  sha256: 7e1cfe0d73ad100c5cc9eed24499c33f819299428e033a26acd5a4323e4244dc

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python {{ python_min }}
    - hatchling
    - pip
  run:
    - python >={{ python_min }}
    - numpy >=1.21
    - scipy

test:
  imports:
    - thztools
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://pypi.org/project/thztools/
  summary: Data analysis software tools for terahertz time-domain spectroscopy (THz-TDS)
  dev_url: https://github.com/dodge-research-group/thztools
  license: MIT
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jsdodge
